locales = ['Egypt', 'Jamaica', 'Miami', 'London', 'Ghana']
print(locales)
# print(sorted(locales))
locales.reverse()
print(locales)
locales.reverse()
print(locales)
locales.sort()
locales.sort(reverse=True)
print(locales)